### ISSUE TITLE
How to train a model on other dataset? 

### ISSUE THREAD

**Issue by shao15xiang** [lin-toto/LICoris#1]
This is a great job. kindly request the author to provide a detailed process for creating ONNX, thank you!

**Comment by lin-toto** [comment]
Unfortunately I lost the original code to do this but it’s really simple to do. My ONNX files are based on CompressAI pretrained models, but you can do it on any other weights as well as long as the model structure is the same.

For factorized you just export net.g_a and g_s and that’s it. Hyperprior compression you can make a function that merges everything together and export that, for decompression export h_s and g_s separately. Then, you can manually compare the structure with my ONNX files.

You may need to tweak the model structure a bit depending on what TensorRT version you’re running, like for older versions you need to change torch.abs to condition check with torch.where because it’s not supported.

**Comment by shao15xiang** [comment]
Thank you for your response.
